# Generated by Django 5.2 on 2025-12-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resident',
            new_name='api_residen_last_na_47cfaf_idx',
            old_name='api_resident_last_na_21e0d8_idx',
        ),
        migrations.RenameIndex(
            model_name='resident',
            new_name='api_residen_apartme_47496b_idx',
            old_name='api_resident_apartme_d2d3d7_idx',
        ),
        migrations.RenameIndex(
            model_name='resident',
            new_name='api_residen_email_44caa2_idx',
            old_name='api_resident_email_12e8d7_idx',
        ),
    ]
